version: 2

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/jest/
      - run:
          name: Run tests
          command: yarn test:ci
      - store_test_results:
          path: ./reports/jest/
      - store_artifacts:
          path: ./reports/jest/
      - store_artifacts:
          path: ./coverage

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
